packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@types/node": ^24.11.0
  "@types/react": ^19.2.14
  "@types/react-dom": ^19.2.3
  eslint: ^9.39.3
  react: ^19.2.4
  react-dom: ^19.2.4
  tsdown: ^0.20.3
  typescript: ^5.9.3
  viem: ^2.46.3
  wagmi: ^2.19.5
  "@tanstack/react-query": ^5.90.21

catalogMode: manual

overrides:
  "@types/node": "catalog:"
  "@types/react": "catalog:"
  "@types/react-dom": "catalog:"
  hardhat: "-"
  react: "catalog:"
  react-dom: "catalog:"
  typescript: "catalog:"
  "react-native": "-"
  "abitype>zod": "-"
