minimumReleaseAge: 1440
blockExoticSubdeps: true
strictDepBuilds: false
catalogMode: manual

packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@tanstack/intent": 0.0.34
  "@tanstack/react-query": ^5.100.9
  "@types/node": ^24.12.2
  "@types/react": ^19.2.14
  "@types/react-dom": ^19.2.3
  react: ^19.2.6
  react-dom: ^19.2.6
  tsdown: ^0.21.10
  typescript: ^6.0.3
  viem: ^2.48.8
  wagmi: ^2.19.5

overrides:
  "@openzeppelin/contracts": "-"
  "@types/node": "catalog:"
  "@types/react": "catalog:"
  "@types/react-dom": "catalog:"
  hardhat: "-"
  react: "catalog:"
  react-dom: "catalog:"
  "react-native": "-"
  "abitype>zod": "-"
  typescript: "catalog:"
