packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@types/node": ^24.10.9
  "@types/react": ^19.2.9
  "@types/react-dom": ^19.2.3
  eslint-plugin-react: ^7.37.5
  eslint-plugin-react-hooks: ^7.0.1
  react: ^19.2.3
  react-dom: ^19.2.3
  typescript: ^5.9.3
  eslint: ^9.39.2
  tsdown: ^0.20.1

catalogMode: manual

overrides:
  "@types/node": "catalog:"
  "@types/react": "catalog:"
  "@types/react-dom": "catalog:"
  react: "catalog:"
  react-dom: "catalog:"
  typescript: "catalog:"
